### ISSUE TITLE
Problem with populate in mongoose 4.12.5

### ISSUE THREAD

**Issue by jubeiam** [niahmiah/mongoose-uuid#8]
mongoose `4.12.5`

I'm trying tu use uuids as _id and it works fine.
Only when i use populate some error occurs.
I've installed this packege and runned test with fail result, can someone help?

Test result bellow:

`$ npm run test

> mongoose-uuid2@2.0.1 test C:\Users\someuser\www\mongoose-uuid
> mocha

  mongoose-uuid
(node:12656) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
(node:12656) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
    √ should cast uuid strings to binary
    √ should convert back to text with toObject()
    √ should save without errors (537ms)
    √ should be found correctly with .find()
    √ should be found correctly with .findById()
    query population
      1) should work
    other scenarios
      √ should get with no value
      2) setting a populated field to uuid string

  6 passing (2s)
  2 failing

  1) mongoose-uuid query population should work:
     Uncaught TypeError: binary.length is not a function
      at model.getter (C:\Users\someuser\www\mongoose-uuid\index.js:12:20)
      at SchemaUUID.SchemaType.applyGetters (C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\schematype.js:723:22)
      at model.Document.get (C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\document.js:971:18)
      at model.get (C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\services\document\compile.js:137:25)
      at C:\Users\someuser\www\mongoose-uuid\test\index.js:119:15
      at C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\query.js:3061:18
      at newTickHandler (C:\Users\someuser\www\mongoose-uuid\node_modules\mpromise\lib\promise.js:234:18)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

  2) mongoose-uuid other scenarios setting a populated field to uuid string:
     Uncaught TypeError: binary.length is not a function
      at model.getter (C:\Users\someuser\www\mongoose-uuid\index.js:12:20)
      at SchemaUUID.SchemaType.applyGetters (C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\schematype.js:723:22)
      at model.Document.get (C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\document.js:971:18)
      at model.get [as dingy] (C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\services\document\compile.js:137:25)
      at C:\Users\someuser\www\mongoose-uuid\test\index.js:166:20
      at C:\Users\someuser\www\mongoose-uuid\node_modules\mongoose\lib\query.js:3061:18
      at newTickHandler (C:\Users\someuser\www\mongoose-uuid\node_modules\mpromise\lib\promise.js:234:18)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mongoose-uuid2@2.0.1 test: `mocha`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mongoose-uuid2@2.0.1 test script 'mocha'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mongoose-uuid2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mongoose-uuid2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mongoose-uuid2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\someuser\www\mongoose-uuid\npm-debug.log`

**Comment by jubeiam** [comment]
I managed to fix it with chnages to getter 
`if(binary instanceof Document) return binary;`
